//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPGRawFotoSelector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPGRawFotoSelector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo clean mode.
        /// </summary>
        internal static string CleanMode {
            get {
                return ResourceManager.GetString("CleanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Column_Header_Files {
            get {
                return ResourceManager.GetString("Column_Header_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configration file is missing!!!.
        /// </summary>
        internal static string Configration_file_is_missing {
            get {
                return ResourceManager.GetString("Configration_file_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type does not support.
        /// </summary>
        internal static string File_type_does_not_support {
            get {
                return ResourceManager.GetString("File_type_does_not_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not in the folder, please refresh the list.
        /// </summary>
        internal static string Please_refresh_the_list {
            get {
                return ResourceManager.GetString("Please_refresh_the_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Select_All {
            get {
                return ResourceManager.GetString("Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Files To Delete.
        /// </summary>
        internal static string SelectFileToDelete {
            get {
                return ResourceManager.GetString("SelectFileToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSelect All.
        /// </summary>
        internal static string UnSelect_All {
            get {
                return ResourceManager.GetString("UnSelect_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo view mode.
        /// </summary>
        internal static string ViewMode {
            get {
                return ResourceManager.GetString("ViewMode", resourceCulture);
            }
        }
    }
}
